variables:
  GIT_STRATEGY: clone

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - shell 
  script:
    - docker compose build

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - echo "📦 Starting Docker Compose...."
    - docker compose down || true
    - docker compose up -d