stages:
  - deploy

variables:
  DEPLOY_USER: root
  DEPLOY_HOST: 192.168.10.6
  DEPLOY_PATH: /home/gitlab-runner/hajjar/site

before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/gitlab_deploy
  - chmod 600 ~/.ssh/gitlab_deploy
  - ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts

deploy:
  image:
    name: 192.168.10.6:5000/node:20
    pull_policy: if-not-present
  stage: deploy
  script:
    - tar czf deploy.tar.gz ./*
    - scp -i ~/.ssh/id_rsa deploy.tar.gz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/

    - ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_HOST "
        cd $DEPLOY_PATH &&
        rm -rf * &&
        tar xzf deploy.tar.gz &&
        docker-compose down &&
        docker-compose up -d --build
      "
  only:
    - main