export const adsEn = [
    {
      id: "ad-001",
      image: "https://via.placeholder.com/300x225",
      stone_type: "Marble",
      origin: "Yazd",
      form: "Slab",
      surface: "Polished",
      source_port: "Iran, Bandar Abbas Rajaei",
      color: "White",
      size: "200x300",
      price: 12000,
      price_unit: "CM2",
      published_at: "2025-06-22",
      is_featured: true,
      is_express: true,
      description:
        "High-quality white marble, suitable for lobbies, bathrooms, and kitchens. Shipping available nationwide.",
    },
    {
      id: "ad-002",
      image: "https://via.placeholder.com/300x225",
      stone_type: "Granite",
      origin: "Zanjan",
      form: "Tile",
      surface: "Matte",
      color: "Black-Gold",
      size: "60x60",
      price: 8500,
      price_unit: "CM2",
      published_at: "2025-06-21",
      is_featured: false,
      is_express: true,
      description:
        "Glossy black granite, highly resistant to impact and abrasion, ideal for outdoor flooring.",
    },
    {
      id: "ad-003",
      image: "https://via.placeholder.com/300x225",
      stone_type: "Travertine",
      origin: "Mahallat",
      form: "Block",
      surface: "Bush-hammered",
      color: "Cream-Yellow",
      weight: "25000",
      price: 45000,
      price_unit: "KG",
      published_at: "2025-06-20",
      is_featured: true,
      is_express: false,
      description:
        "Cream travertine block, suitable for export. Competitive price and guaranteed quality.",
    },
    {
      id: "ad-004",
      image: "https://via.placeholder.com/300x225",
      stone_type: "Marble Limestone",
      origin: "Dehbid",
      form: "Slab",
      surface: "Polished",
      source_port: "Iran, Bandar Abbas Rajaei",
      color: "Beige",
      size: "180x250",
      price: 15000,
      price_unit: "CM2",
      published_at: "2025-06-18",
      is_featured: false,
      is_express: false,
      description:
        "Light beige Dehbid marble, ideal for interior flooring and luxury decoration.",
    },
    {
      id: "ad-005",
      image: "https://via.placeholder.com/300x225",
      stone_type: "Marble",
      origin: "Kashan",
      form: "Tile",
      surface: "Leather finish",
      source_port: "Iran, Bandar Abbas Rajaei",
      color: "Green",
      size: "30x60",
      price: 9500,
      price_unit: "CM2",
      published_at: "2025-06-17",
      is_featured: true,
      is_express: false,
      description:
        "Green marble with leather finish, perfect for unique interior designs.",
    },
    {
      id: "ad-006",
      image: "https://via.placeholder.com/300x225",
      stone_type: "Basalt",
      origin: "Tabriz",
      form: "Block",
      surface: "Raw",
      color: "Dark Gray",
      weight: "30000",
      price: 300000,
      price_unit: "KG",
      published_at: "2025-06-15",
      is_featured: false,
      is_express: true,
      description:
        "Dark gray basalt, ideal for large-scale industrial and construction projects.",
    },
    {
      id: "ad-007",
      image: "https://via.placeholder.com/300x225",
      stone_type: "Travertine",
      origin: "Hamedan",
      form: "Tile",
      surface: "Matte",
      source_port: "Iran, Bandar Abbas Rajaei",
      color: "Brown",
      size: "40x40",
      price: 7800,
      price_unit: "CM2",
      published_at: "2025-06-14",
      is_featured: true,
      is_express: true,
      description:
        "Brown travertine with uniform texture, ideal for facades and staircases.",
    },
    {
      id: "ad-008",
      image: "https://via.placeholder.com/300x225",
      stone_type: "Crystal",
      origin: "Neyriz",
      form: "Slab",
      surface: "Polished",
      source_port: "Iran, Bandar Abbas Rajaei",
      color: "White-Blue",
      size: "200x300",
      price: 17000,
      price_unit: "CM2",
      published_at: "2025-06-13",
      is_featured: false,
      is_express: false,
      description:
        "Neyriz crystal stone with unique blue veins, perfect for luxury projects.",
    },
    {
      id: "ad-009",
      image: "https://via.placeholder.com/300x225",
      stone_type: "Marble Limestone",
      origin: "Kerman",
      form: "Tile",
      surface: "Polished",
      source_port: "Iran, Bandar Abbas Rajaei",
      color: "Pink",
      size: "50x50",
      price: 9900,
      price_unit: "CM2",
      published_at: "2025-06-12",
      is_featured: true,
      is_express: true,
      description:
        "Rare pink marble limestone from Kerman, ideal for elegant interior spaces.",
    },
    {
      id: "ad-010",
      image: "https://via.placeholder.com/300x225",
      stone_type: "Sandstone",
      origin: "Isfahan",
      form: "Block",
      surface: "Raw",
      color: "Beige",
      weight: "20000",
      price: 32000,
      price_unit: "KG",
      published_at: "2025-06-10",
      is_featured: false,
      is_express: false,
      description: "Beige sandstone, ideal for classic exterior facade projects.",
    },
  ]; 