import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import { ThemeProvider } from "next-themes";
import MobileBottomNav from "@/components/shared/footer/mobile-bottom-nav";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const poppins = localFont({
  src: "../../public/fonts/Poppins-Medium.ttf",
  display: "swap",
  variable: "--font-poppins",
  preload: true,
  fallback: ["system-ui", "sans-serif"],
});

const yekanBakh = localFont({
  src: "../../public/fonts/YekanBakhFaNum-Regular.woff",
  display: "swap",
  variable: "--font-yekan",
  preload: true,
  fallback: ["system-ui", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const isRTL = locale === "fa";
  const dir = isRTL ? "rtl" : "ltr";
  const font = isRTL ? yekanBakh : poppins;

  return (
    <html lang={locale} dir={dir} suppressHydrationWarning>
      <body className={`${font.className} ${isRTL ? "rtl" : ""}`}>
        <NextIntlClientProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header />
            {children}
            <Footer />
            <MobileBottomNav />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
