export const adsFa =[
    {
      "id": "ad-001",
      "image": "https://via.placeholder.com/300x225",
      "stone_type": "مرمر",
      "origin": "یزد",
      "form": "اسلب",
      "surface": "پولیش",
      "source_port": "ایران، بندر عباس رجایی",
      "color": "سفید",
      "size": "200x300",
      "price": 12000,
      "price_unit": "CM2",
      "published_at": "2025-06-22",
      "is_featured": true,
      "is_express": true,
      "description": "سنگ مرمر سفید با کیفیت بالا، مناسب برای لابی، سرویس بهداشتی و آشپزخانه. ارسال به تمام نقاط کشور."
    },
    {
      "id": "ad-002",
      "image": "https://via.placeholder.com/300x225",
      "stone_type": "گرانیت",
      "origin": "زنجان",
      "form": "تایل",
      "surface": "مات",
      "color": "مشکی طلایی",
      "size": "60x60",
      "price": 8500,
      "price_unit": "CM2",
      "published_at": "2025-06-21",
      "is_featured": false,
      "is_express": true,
      "description": "گرانیت مشکی براق، بسیار مقاوم در برابر ضربه و سایش، مناسب برای کف‌سازی محوطه‌ها."
    },
    {
      "id": "ad-003",
      "image": "https://via.placeholder.com/300x225",
      "stone_type": "تراورتن",
      "origin": "محلات",
      "form": "بلوک",
      "surface": "تیشه‌ای",
      "color": "کرم زرد",
      "weight": "25000",
      "price": 45000,
      "price_unit": "KG",
      "published_at": "2025-06-20",
      "is_featured": true,
      "is_express": false,
      "description": "بلوک تراورتن کرم رنگ، مناسب برای صادرات. قیمت مناسب و کیفیت تضمینی."
    },
    {
      "id": "ad-004",
      "image": "https://via.placeholder.com/300x225",
      "stone_type": "مرمریت",
      "origin": "دهبید",
      "form": "اسلب",
      "surface": "پولیش",
      "source_port": "ایران، بندر عباس رجایی",
      "color": "کرم",
      "size": "180x250",
      "price": 15000,
      "price_unit": "CM2",
      "published_at": "2025-06-18",
      "is_featured": false,
      "is_express": false,
      "description": "سنگ دهبید کرم روشن مناسب برای کف‌پوش‌های داخلی و دکوراسیون لوکس."
    },
    {
      "id": "ad-005",
      "image": "https://via.placeholder.com/300x225",
      "stone_type": "مرمر",
      "origin": "کاشان",
      "form": "تایل",
      "surface": "چرمی",
      "source_port": "ایران، بندر عباس رجایی",
      "color": "سبز",
      "size": "30x60",
      "price": 9500,
      "price_unit": "CM2",
      "published_at": "2025-06-17",
      "is_featured": true,
      "is_express": false,
      "description": "مرمر سبز با سطح چرمی، مناسب برای طراحی‌های خاص داخلی."
    },
    {
      "id": "ad-006",
      "image": "https://via.placeholder.com/300x225",
      "stone_type": "بازالت",
      "origin": "تبریز",
      "form": "بلوک",
      "surface": "خام",
      "color": "خاکستری",
      "weight": "30000",
      "price": 300000,
      "price_unit": "KG",
      "published_at": "2025-06-15",
      "is_featured": false,
      "is_express": true,
      "description": "بازالت خاکستری مناسب برای پروژه‌های صنعتی و عمرانی بزرگ."
    },
    {
      "id": "ad-007",
      "image": "https://via.placeholder.com/300x225",
      "stone_type": "تراورتن",
      "origin": "همدان",
      "form": "تایل",
      "surface": "مات",
      "source_port": "ایران، بندر عباس رجایی",
      "color": "قهوه‌ای",
      "size": "40x40",
      "price": 7800,
      "price_unit": "CM2",
      "published_at": "2025-06-14",
      "is_featured": true,
      "is_express": true,
      "description": "تراورتن قهوه‌ای با بافت یکنواخت و مناسب برای نما و راه‌پله."
    },
    {
      "id": "ad-008",
      "image": "https://via.placeholder.com/300x225",
      "stone_type": "کریستال",
      "origin": "نی‌ریز",
      "form": "اسلب",
      "surface": "پولیش",
      "source_port": "ایران، بندر عباس رجایی",
      "color": "سفید آبی",
      "size": "200x300",
      "price": 17000,
      "price_unit": "CM2",
      "published_at": "2025-06-13",
      "is_featured": false,
      "is_express": false,
      "description": "کریستال نی‌ریز با رگه‌های آبی خاص، مناسب برای پروژه‌های لوکس."
    },
    {
      "id": "ad-009",
      "image": "https://via.placeholder.com/300x225",
      "stone_type": "مرمریت",
      "origin": "کرمان",
      "form": "تایل",
      "surface": "پولیش",
      "source_port": "ایران، بندر عباس رجایی",
      "color": "صورتی",
      "size": "50x50",
      "price": 9900,
      "price_unit": "CM2",
      "published_at": "2025-06-12",
      "is_featured": true,
      "is_express": true,
      "description": "مرمریت صورتی کم‌نظیر از معادن کرمان، مناسب فضای داخلی و دکوراسیون خاص."
    },
    {
      "id": "ad-010",
      "image": "https://via.placeholder.com/300x225",
      "stone_type": "سنداستون",
      "origin": "اصفهان",
      "form": "بلوک",
      "surface": "خام",
      "color": "بژ",
      "weight": "20000",
      "price": 32000,
      "price_unit": "KG",
      "published_at": "2025-06-10",
      "is_featured": false,
      "is_express": false,
      "description": "سنداستون بژ، مناسب پروژه‌های نماکاری کلاسیک در فضای باز."
    }
  ]
  
  